hetic_search_homepage:
    pattern:  /
    defaults: { _controller: HeticSearchBundle:Default:index }
    
hetic_search_view:
    pattern:  /film/{id}
    defaults: { _controller: HeticSearchBundle:Default:see }
    
hetic_search_result:
    pattern:  /result
    defaults: { _controller: HeticSearchBundle:Default:result }
    
hetic_search_about:
    pattern:  /about
    defaults: { _controller: HeticSearchBundle:Default:about }

hetic_search_contact:
    pattern:  /contact
    defaults: { _controller: HeticSearchBundle:Default:contact }