parameters:
#    hetic_search.example.class: Hetic\SearchBundle\Example

services:
#    hetic_search.example:
#        class: %hetic_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
