Film:
    type: entity
    table: film
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 120
            fixed: false
            nullable: true
        synopsis:
            type: text
            nullable: true
        vues:
            type: integer
            unsigned: false
            nullable: false
        description:
            type: text
            nullable: true
        dateParution:
            type: datetime
            nullable: true
            column: date_parution
        dateCreated:
            type: datetime
            nullable: true
            column: date_created
    manyToMany:
        tag:
            targetEntity: Tag
            cascade: {  }
            mappedBy: null
            inversedBy: film
            joinTable:
                name: appartenir
                joinColumns:
                    -
                        name: film_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: tag_id
                        referencedColumnName: id
            orderBy: null
        acteur:
            targetEntity: Acteur
            cascade: {  }
            mappedBy: film
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        category:
            targetEntity: Categorie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
