Tag:
    type: entity
    table: tag
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 120
            fixed: false
            nullable: true
        description:
            type: text
            nullable: true
    manyToMany:
        film:
            targetEntity: Film
            cascade: {  }
            mappedBy: tag
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
